<template>
<main class="reports" dir="rtl"><header class="head"><div><small>گزارش یکپارچه</small><h1>گزارشات کلینیک</h1></div><button @click="exportReport">خروجی Excel</button></header>
 <section class="filters"><label>از<input v-model="filters.from" @change="load" /></label><label>تا<input v-model="filters.to" @change="load" /></label><button @click="load">بروزرسانی</button></section>
 <div v-if="loading" class="loading"><i></i>در حال ساخت گزارش از داده‌های کلینیک…</div><div v-else-if="error" class="error">{{ error }}</div>
 <template v-else-if="report"><section class="timeline"><h2>تایم‌لاین فروش</h2><div v-if="!report.sales_timeline.length" class="empty">در این بازه خدمت انجام‌شده‌ای ثبت نشده است.</div><div v-else class="timeline-bars"><article v-for="item in report.sales_timeline" :key="item.date"><b :style="{height:bar(item.revenue)}"></b><strong>{{ money(item.revenue) }}</strong><small>{{ item.date }}</small></article></div></section>
 <section class="kpis"><ReportCard title="درآمد خدمات" :value="money(report.kpis.recognized_revenue)" hint="انجام‌شده" @open="drill('recognized_revenue')"/><ReportCard title="وصول نقدی" :value="money(report.kpis.cash_collected)" hint="پرداخت‌شده"/><ReportCard title="هزینه‌ها" :value="money(report.kpis.expenses)" @open="drill('expenses')"/><ReportCard title="هزینه پزشک" :value="money(report.kpis.doctor_cost)"/><ReportCard title="حقوق پرسنل" :value="money(report.kpis.staff_cost)"/><ReportCard title="سود خالص" :value="money(report.kpis.net_profit)"/><ReportCard title="تخمین درآمد آینده" :value="money(report.kpis.forecast_revenue)" :hint="`کسر ${fa(report.forecast.previous_month_cancellation_rate)}٪ کنسلی ماه قبل`"/></section>
 <section class="grid"><article class="panel"><h2>نرخ کنسلی</h2><strong class="rate">{{ fa(report.cancellation.rate) }}٪</strong><p>آمد: {{ fa(report.cancellation.arrived) }} · کنسل: {{ fa(report.cancellation.cancelled) }} · پاسخ نداد: {{ fa(report.cancellation.no_answer) }}</p></article><article class="panel"><h2>گنجایش مجموعه</h2><strong class="rate">{{ fa(report.capacity.percent) }}٪</strong><p>درآمد {{ money(report.capacity.revenue) }} از سقف {{ money(report.capacity.limit) }}</p></article><article class="panel"><h2>مشتریان وفادار و ریزش</h2><p>مشتری انجام‌کار: <b>{{ fa(report.loyalty.completed_customers) }}</b></p><p>وفادار: <b>{{ fa(report.loyalty.loyal) }}</b> · ریزش: <b>{{ fa(report.loyalty.churned) }}</b></p></article></section>
 <section class="panel wide"><h2>هزینه‌ها</h2><div class="rows"><p v-for="item in report.expenses.items" :key="item.category"><span>{{ item.category }}</span><b>{{ money(item.amount) }}</b></p><p v-if="!report.expenses.items.length">هزینه‌ای در این بازه ثبت نشده است.</p></div></section>
 <section class="two"><article class="panel"><h2>پزشکان و پرسنل</h2><div class="rows"><p v-for="row in report.resources" :key="`${row.type}-${row.id}`"><span>{{ row.name }} <small>({{ row.type === 'doctor' ? 'پزشک' : 'پرسنل' }})</small></span><b>{{ money(row.total) }}</b><em>حقوق {{ money(row.salary) }} · پورسانت {{ money(row.commission) }} · حضور {{ money(row.attendance) }} · تعدیل {{ money(row.adjustment) }}</em><em v-if="row.target">تارگت: {{ money(row.target) }} — {{ row.target_reached ? 'رسیده به تارگت ✓' : 'هنوز نرسیده' }}</em></p><p v-if="!report.resources.length">داده حقوقی ثبت نشده است.</p></div></article><article class="panel"><h2>کمپین‌ها و CAC</h2><div class="rows"><p v-for="row in report.campaigns" :key="row.campaign_id"><span>{{ row.name }}</span><b>{{ money(row.cac) }}</b><em>هزینه {{ money(row.cost) }} · {{ fa(row.appointments) }} نوبت · کیفیت {{ fa(row.quality) }}٪</em></p><p v-if="!report.campaigns.length">کمپین هزینه‌دار ثبت نشده است.</p></div></article></section>
 <section class="two"><article class="panel"><h2>کانال‌های تبلیغاتی</h2><div class="rows"><p v-for="row in report.channels" :key="row.name"><span>{{ row.name }}</span><b>{{ fa(row.completed) }} انجام‌شده</b><em>درآمد {{ money(row.revenue) }}</em></p></div></article><article class="panel"><h2>رضایت‌مندی</h2><div class="rows"><p v-for="row in report.satisfaction" :key="row.key"><span>{{ row.label }}</span><b>{{ fa(row.percent) }}٪</b><em>{{ fa(row.count) }} پاسخ</em></p><p v-if="!report.satisfaction.length">هنوز پاسخی ثبت نشده است.</p></div></article></section>
 <section class="two"><article class="panel"><h2>کیفیت عکس بر اساس تگ</h2><div class="rows"><p v-for="row in report.photo_quality" :key="row.tag"><span>{{ row.tag }}</span><b>{{ fa(row.percent) }}٪</b><em>{{ fa(row.qualified) }} از {{ fa(row.total) }} تأیید</em></p><p v-if="!report.photo_quality.length">ارزیابی کیفیتی ثبت نشده است.</p></div></article><article class="panel"><h2>تولدهای این ماه</h2><div class="birthdays"><button v-for="row in report.birthdays" :key="row.id" @click="$emit('open-patient',row.id)"><span>{{ row.name }}</span><small>{{ row.birth_date }}</small></button><p v-if="!report.birthdays.length">تولدی در این ماه ثبت نشده است.</p></div></article></section>
 <section class="panel wide"><h2>پردرآمدترین / پرسودترین خدمات</h2><div class="tabs"><button :class="{active:sort==='revenue'}" @click="sort='revenue'">پردرآمدترین</button><button :class="{active:sort==='profit'}" @click="sort='profit'">پرسودترین</button></div><div class="rows"><p v-for="row in sortedServices" :key="row.name"><span>{{ row.name }}</span><b>{{ money(row[sort]) }}</b></p></div></section></template>
 <div v-if="drillData" class="modal" @click.self="drillData=null"><section><button @click="drillData=null">×</button><h2>{{ drillData.metric }}</h2><pre>{{ prettyDrill }}</pre></section></div></main>
</template>
<script>
import axios from 'axios'; import ReportCard from './ReportCard.vue';
export default {components:{ReportCard},emits:['open-patient'],data:()=>({filters:{from:'1405/02/01',to:'1405/04/31'},report:null,loading:false,error:'',sort:'revenue',drillData:null}),computed:{sortedServices(){return [...(this.report?.services||[])].sort((a,b)=>b[this.sort]-a[this.sort]);},prettyDrill(){return JSON.stringify(this.drillData,null,2)}},mounted(){this.load()},methods:{fa(v){return Number(v||0).toLocaleString('fa-IR')},money(v){return `${this.fa(v)} تومان`},bar(v){const max=Math.max(...(this.report?.sales_timeline||[]).map(x=>x.revenue),1);return `${Math.max(8,Number(v)/max*130)}px`},async load(){this.loading=true;this.error='';try{const {data}=await axios.get('/api/reports/dashboard',{params:this.filters});this.report=data}catch(e){this.error=e.response?.data?.message||'گزارش دریافت نشد.'}finally{this.loading=false}},async drill(metric){try{const {data}=await axios.get(`/api/reports/drilldown/${metric}`,{params:this.filters});this.drillData=data}catch(e){this.error='جزئیات دریافت نشد.'}},exportReport(){const q=new URLSearchParams(this.filters);window.open(`/api/reports/export?${q}`,'_blank')}}}
</script>
<style scoped>.reports{min-height:calc(100vh - 140px);padding:22px;background:#f1f4f9;color:#0f172a}.head,.filters,.two{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap}.head h1,.panel h2,.timeline h2{margin:4px 0;font-size:20px}.head small{color:#2563eb;font-weight:900}.head button,.filters button,.tabs button{border:0;border-radius:10px;padding:10px 14px;background:#2563eb;color:white;font-family:inherit;font-weight:900;cursor:pointer}.filters{margin:16px 0;padding:14px;border-radius:16px;background:#fff}.filters label{display:grid;gap:5px;font-size:11px;font-weight:900}.filters input{height:38px;border:1px solid #cbd5e1;border-radius:9px;padding:0 10px;font-family:inherit}.timeline,.panel{margin-bottom:16px;padding:18px;border:1px solid #e2e8f0;border-radius:18px;background:#fff;box-shadow:0 8px 24px rgba(15,23,42,.04)}.timeline-bars{height:190px;display:flex;gap:11px;align-items:end;overflow:auto}.timeline-bars article{min-width:88px;display:grid;gap:5px;justify-items:center}.timeline-bars b{width:28px;border-radius:8px 8px 0 0;background:linear-gradient(#38bdf8,#2563eb)}.timeline-bars strong{font-size:10px}.timeline-bars small,.rows em{color:#64748b;font-size:9px;font-style:normal}.kpis,.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(175px,1fr));gap:12px;margin-bottom:16px}.grid .panel{margin:0}.rate{font-size:30px;color:#2563eb}.rows{display:grid;gap:8px}.rows p{display:grid;grid-template-columns:1fr auto;gap:5px;margin:0;padding:10px;border-radius:10px;background:#f8fafc;font-size:12px}.rows em{grid-column:1/-1}.two{align-items:stretch}.two>.panel{width:calc(50% - 6px)}.wide{width:100%}.tabs{display:flex;gap:6px;margin-bottom:10px}.tabs button{background:#e2e8f0;color:#475569}.tabs button.active{background:#2563eb;color:#fff}.birthdays{display:grid;gap:6px;max-height:230px;overflow:auto}.birthdays button{display:flex;justify-content:space-between;border:0;border-radius:9px;padding:10px;background:#f8fafc;font-family:inherit;cursor:pointer}.birthdays small{color:#64748b}.loading,.error,.empty{padding:34px;text-align:center;border-radius:16px;background:#fff;color:#64748b}.loading i{display:inline-block;width:19px;height:19px;margin-left:8px;border:3px solid #bfdbfe;border-top-color:#2563eb;border-radius:50%;animation:s .7s linear infinite}.error{color:#b91c1c}.modal{position:fixed;inset:0;z-index:10000;display:grid;place-items:center;padding:16px;background:rgba(15,23,42,.55)}.modal section{width:min(700px,96vw);max-height:80vh;overflow:auto;padding:20px;border-radius:16px;background:white}.modal button{float:left;border:0;background:#e2e8f0;border-radius:8px;font-size:20px}@keyframes s{to{transform:rotate(360deg)}}@media(max-width:800px){.reports{padding:12px}.two>.panel{width:100%}}</style>
